---
services:  
    mlflow:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            #- ./data:/app/data  # 挂载 data 目录到容器
            - ./mlruns:/app/mlruns  # 持久化 mlruns
        ports:
            - "6000:5000"

        # command: services:

        command: mlflow server --host 0.0.0.0 --port 5000 \
             --backend-store-uri sqlite:///mlflow.db \
             --default-artifact-root ./mlruns


        environment:
            MLFLOW_TRACKING_URI: http://localhost:5000 
            MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
        restart: unless-stopped