name: CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pytest-cov mlflow

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint --disable=E,F,C,W *.py

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --cov=main --cov=mylib test_*.py

      - name: Prepare mlruns directory
        run: |
          mkdir -p mlruns
          chmod -R u+w mlruns
  
      - name: Set MLflow environment variables
        run: |
          echo "MLFLOW_TRACKING_URI=file:./mlruns" >> $GITHUB_ENV
          echo "MLFLOW_ARTIFACT_URI=file:./mlruns" >> $GITHUB_ENV

      - name: Debug MLflow paths
        run: |
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
          echo "MLFLOW_ARTIFACT_URI=$MLFLOW_ARTIFACT_URI"
          ls -l $(pwd)/mlruns

      - name: Run MLflow model
        run: make ml_run