name: CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pytest

      - name: Install dependencies
        run: |
          pip install pylint
          
      - name: Set PYTHONPATH
        run: export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov



      - name: Run Pylint
        run: $(which pylint) --disable=E,F,C,W *.py


      - name: Run tests
        run: make test


      - name: Format code
        run: make format


      - name: Generate and push artifacts
        run: make generate_and_push


      - name: Deploy application
        run: make deploy

      - name: Run model
        run: make ml_run