name: CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pytest pytest-cov

      - name: Install dependencies
        run: |
          pip install pylint
  
      - name: Run Pylint
        run: $(which pylint) --disable=E,F,C,W *.py


      - name: Run tests
        run: make test


      - name: Format code
        run: make format


      - name: Generate and push artifacts
        run: make generate_and_push


      - name: Deploy application
        run: make deploy

      - name: Run model
        run: make ml_run