name: Extract Data

on: [push]

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install -r requirements.txt

    - name: Configure Kaggle API
      run: |
        mkdir -p ~/.kaggle
        echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
      env:
        KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

    - name: Extract Data
      run: make extract
