name: Extract Data

on: [push]

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install -r requirements.txt

    - name: Install Kaggle CLI
      run: |
        pip install kaggle
        mkdir -p ~/.kaggle
        echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Run Make Extract
      run: make extract
      env:
        KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
